version: "3.8"
services:
  influx:
    env_file: .env
    image: influxdb:latest
    ports:
      - "${influx_port}:8086"
    volumes:
      - ./influx/influxdb:/var/lib/influxdb2
      - ./influx/config:/etc/influxdb:ro
    restart: always
    # healthcheck:
    #   test: pg_isready -U ${DB_USER}
    #   interval: 2s
    #   timeout: 3s
    #   retries: 40
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    mem_limit: 500M
    mem_reservation: 500m
    cpus: 1

  grafana:
    env_file: .env
    image: grafana/grafana:latest
    ports:
      - "${grafana_port}:3000"
    volumes:
      - grafana:/var/lib/grafana
    links:
      - influx
    restart: always
    # healthcheck:
    #   test: pg_isready -U ${DB_USER}
    #   interval: 2s
    #   timeout: 3s
    #   retries: 40
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    mem_limit: 500M
    mem_reservation: 500m
    cpus: 1

  telegraf:
    env_file: .env
    image: telegraf:latest
    network_mode: "host"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    # healthcheck:
    #   test: pg_isready -U ${DB_USER}
    #   interval: 2s
    #   timeout: 3s
    #   retries: 40
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    mem_limit: 500M
    mem_reservation: 500m
    cpus: 1

volumes:
  grafana:
    name: grafana
    external: true
